/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SubmitRouteImport } from './routes/submit'
import { Route as StoriesRouteImport } from './routes/stories'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ContributorsRouteImport } from './routes/contributors'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StoriesSlugRouteImport } from './routes/stories.$slug'
import { Route as ContributorsSlugRouteImport } from './routes/contributors.$slug'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminSubmissionsRouteImport } from './routes/_authenticated/admin.submissions'
import { Route as AuthenticatedAdminStoriesRouteImport } from './routes/_authenticated/admin.stories'
import { Route as AuthenticatedAdminContributorsRouteImport } from './routes/_authenticated/admin.contributors'

const SubmitRoute = SubmitRouteImport.update({
  id: '/submit',
  path: '/submit',
  getParentRoute: () => rootRouteImport,
} as any)
const StoriesRoute = StoriesRouteImport.update({
  id: '/stories',
  path: '/stories',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ContributorsRoute = ContributorsRouteImport.update({
  id: '/contributors',
  path: '/contributors',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StoriesSlugRoute = StoriesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => StoriesRoute,
} as any)
const ContributorsSlugRoute = ContributorsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ContributorsRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminSubmissionsRoute =
  AuthenticatedAdminSubmissionsRouteImport.update({
    id: '/admin/submissions',
    path: '/admin/submissions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminStoriesRoute =
  AuthenticatedAdminStoriesRouteImport.update({
    id: '/admin/stories',
    path: '/admin/stories',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminContributorsRoute =
  AuthenticatedAdminContributorsRouteImport.update({
    id: '/admin/contributors',
    path: '/admin/contributors',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contributors': typeof ContributorsRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/stories': typeof StoriesRouteWithChildren
  '/submit': typeof SubmitRoute
  '/contributors/$slug': typeof ContributorsSlugRoute
  '/stories/$slug': typeof StoriesSlugRoute
  '/admin/contributors': typeof AuthenticatedAdminContributorsRoute
  '/admin/stories': typeof AuthenticatedAdminStoriesRoute
  '/admin/submissions': typeof AuthenticatedAdminSubmissionsRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contributors': typeof ContributorsRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/stories': typeof StoriesRouteWithChildren
  '/submit': typeof SubmitRoute
  '/contributors/$slug': typeof ContributorsSlugRoute
  '/stories/$slug': typeof StoriesSlugRoute
  '/admin/contributors': typeof AuthenticatedAdminContributorsRoute
  '/admin/stories': typeof AuthenticatedAdminStoriesRoute
  '/admin/submissions': typeof AuthenticatedAdminSubmissionsRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contributors': typeof ContributorsRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/stories': typeof StoriesRouteWithChildren
  '/submit': typeof SubmitRoute
  '/contributors/$slug': typeof ContributorsSlugRoute
  '/stories/$slug': typeof StoriesSlugRoute
  '/_authenticated/admin/contributors': typeof AuthenticatedAdminContributorsRoute
  '/_authenticated/admin/stories': typeof AuthenticatedAdminStoriesRoute
  '/_authenticated/admin/submissions': typeof AuthenticatedAdminSubmissionsRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/contributors'
    | '/sitemap.xml'
    | '/stories'
    | '/submit'
    | '/contributors/$slug'
    | '/stories/$slug'
    | '/admin/contributors'
    | '/admin/stories'
    | '/admin/submissions'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/contributors'
    | '/sitemap.xml'
    | '/stories'
    | '/submit'
    | '/contributors/$slug'
    | '/stories/$slug'
    | '/admin/contributors'
    | '/admin/stories'
    | '/admin/submissions'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/contributors'
    | '/sitemap.xml'
    | '/stories'
    | '/submit'
    | '/contributors/$slug'
    | '/stories/$slug'
    | '/_authenticated/admin/contributors'
    | '/_authenticated/admin/stories'
    | '/_authenticated/admin/submissions'
    | '/_authenticated/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  ContributorsRoute: typeof ContributorsRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StoriesRoute: typeof StoriesRouteWithChildren
  SubmitRoute: typeof SubmitRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/submit': {
      id: '/submit'
      path: '/submit'
      fullPath: '/submit'
      preLoaderRoute: typeof SubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stories': {
      id: '/stories'
      path: '/stories'
      fullPath: '/stories'
      preLoaderRoute: typeof StoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contributors': {
      id: '/contributors'
      path: '/contributors'
      fullPath: '/contributors'
      preLoaderRoute: typeof ContributorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stories/$slug': {
      id: '/stories/$slug'
      path: '/$slug'
      fullPath: '/stories/$slug'
      preLoaderRoute: typeof StoriesSlugRouteImport
      parentRoute: typeof StoriesRoute
    }
    '/contributors/$slug': {
      id: '/contributors/$slug'
      path: '/$slug'
      fullPath: '/contributors/$slug'
      preLoaderRoute: typeof ContributorsSlugRouteImport
      parentRoute: typeof ContributorsRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/submissions': {
      id: '/_authenticated/admin/submissions'
      path: '/admin/submissions'
      fullPath: '/admin/submissions'
      preLoaderRoute: typeof AuthenticatedAdminSubmissionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/stories': {
      id: '/_authenticated/admin/stories'
      path: '/admin/stories'
      fullPath: '/admin/stories'
      preLoaderRoute: typeof AuthenticatedAdminStoriesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/contributors': {
      id: '/_authenticated/admin/contributors'
      path: '/admin/contributors'
      fullPath: '/admin/contributors'
      preLoaderRoute: typeof AuthenticatedAdminContributorsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminContributorsRoute: typeof AuthenticatedAdminContributorsRoute
  AuthenticatedAdminStoriesRoute: typeof AuthenticatedAdminStoriesRoute
  AuthenticatedAdminSubmissionsRoute: typeof AuthenticatedAdminSubmissionsRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminContributorsRoute: AuthenticatedAdminContributorsRoute,
  AuthenticatedAdminStoriesRoute: AuthenticatedAdminStoriesRoute,
  AuthenticatedAdminSubmissionsRoute: AuthenticatedAdminSubmissionsRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface ContributorsRouteChildren {
  ContributorsSlugRoute: typeof ContributorsSlugRoute
}

const ContributorsRouteChildren: ContributorsRouteChildren = {
  ContributorsSlugRoute: ContributorsSlugRoute,
}

const ContributorsRouteWithChildren = ContributorsRoute._addFileChildren(
  ContributorsRouteChildren,
)

interface StoriesRouteChildren {
  StoriesSlugRoute: typeof StoriesSlugRoute
}

const StoriesRouteChildren: StoriesRouteChildren = {
  StoriesSlugRoute: StoriesSlugRoute,
}

const StoriesRouteWithChildren =
  StoriesRoute._addFileChildren(StoriesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  ContributorsRoute: ContributorsRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StoriesRoute: StoriesRouteWithChildren,
  SubmitRoute: SubmitRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
